
class AECBaseAdder:
    def get_example_output(self):
        '''
        returns: list of numpy arrays with the correct shape and dtype of the result
        '''

    def set_generate_callback(self, on_generate):
        '''
        args:
        on_generate: The callback that is called when a new transition is generated
        '''

    def add(self, agent, obs, action, rewards, dones, env_dones, passes, info):
        '''
        an agent's,
        observation, reward, done, and info
        generated by the environment
        passes: are null environment steps that should be ignored
        '''
        #if np.any(dones) or np.any(env_dones):
