
class AECAdder:
    def __init__(self, on_generate):
        '''
        args:
        on_generate: The callback that is called when a new transition is generated
        '''

    def add(self, agent, obs, rewards, dones, env_dones, passes, info):
        '''
        an agent's,
        observation, reward, done, and info
        generated by the environment
        passes: are null environment steps that should be ignored
        '''
        #if np.any(dones) or np.any(env_dones):
