
class TransitionAdder:
    def __init__(self, on_generate):
        '''
        args:
        on_generate: The callback that is called when a new transition is generated
        '''

    def add(self, obs, rew, done, info):
        '''
        the observation, reward, done, and info
        generated by the environment
        '''
